name: handson

services:
  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: handson1!
      MYSQL_DATABASE: handson-db
      MYSQL_USER: handson-user
      MYSQL_PASSWORD: handson1!
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
# - CPU 성능 제한을 위한 설정
#    deploy:
#      resources:
#        limits:
#          cpus: "0.05"

  redis:
    image: redis:7
    ports:
      - "16379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
